# Generated by Django 3.2 on 2021-04-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210417_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tags',
            new_name='tags_ques',
        ),
    ]
